name: Build & Push Alist Docker Image

on:
  push:
    branches: [ 'main' ]

jobs:
  build-and-push:
    name: Build & Push Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 登录 DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 构建并推送镜像（去掉多平台，只构建 amd64）
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: alizaccc/alist-custom:latest
